In [179]:
import numpy as np

In [180]:
## Create `np` directly
arr1_1 = np.array([1,5,10])
arr1_2 = np.array([ [1,5,9], [4,6,7] ])

# Create `np` from list
list1 = [1,2,3]
arr2_1 = np.asarray(list1)

list2 = list()
list2.append([1,2,3])
list2.append([3,4,5])
arr2_2 = np.asarray(list2)

# Convert `np` to list
l1 = arr2_1.tolist()
l2 = arr2_2.tolist()

# Create `np` from zeros
arr3_1 = np.zeros(4)
arr3_2 = np.ones((4,2))

# Create `np` from pre-filled integers
arr4_2 = np.full( (4,2), 9 )

# Create diagonal matrix in `np`
arr5_2 = np.eye(3)

# Create `np` random
arr6_2 = np.random.random((4,3))

In [181]:
arr6_2

array([[0.55295033, 0.84603376, 0.56715477],
       [0.36110834, 0.13580256, 0.73910518],
       [0.93536175, 0.60760092, 0.98104011],
       [0.99901473, 0.31592869, 0.85418745]])

In [182]:
## slicing and indexing
row_slice = arr6_2[0:2, :]
col_slice = arr6_2[:, 0:2]

## Select individual elements from `np` array
row_indices = np.array([1, 2, 2, 0])
col_indices = np.array([0, 1, 2, 0])
selected_slice = arr6_2[row_indices, col_indices]

## Change selected indices elements
arr6_2[row_indices, col_indices] += 100

In [187]:
## Filter functions
filter = arr6_2 > 20
arr6_2[filter]
# Same as above
arr6_2[(arr6_2 > 15)]

array([100.55295033, 100.36110834, 100.60760092, 100.98104011])

In [201]:
## Arithmetic operations

arr1 = np.full((3,2), 5.0)
arr2 = np.full((3,2), 3.0)

# add
arr1 + arr2
# same thing as above
np.add(arr1, arr2)

# substract
arr1 - arr2
# same thing as above
np.subtract(arr1, arr2)

# multiply
arr1 * arr2
# same thing as above
np.multiply(arr1, arr2)

# divide
arr1 / arr2
# same thing as above
np.divide(arr1, arr2)

# square root
np.sqrt(arr1)

# exponent
np.exp(arr1)

array([[148.4131591, 148.4131591],
       [148.4131591, 148.4131591],
       [148.4131591, 148.4131591]])

In [229]:
## Statistics operations

arr1 = np.array([[2,5],[4,8],[7,3]])

# mean
np.mean(arr1)
np.mean(arr1, axis=1) # mean by row
np.mean(arr1, axis=0) # mean by col

# sum
np.sum(arr1)
np.sum(arr1, axis=1) # sum by row
np.sum(arr1, axis=0) # sum by col

# median
np.median(arr1)
np.median(arr1, axis=1) # median by row
np.median(arr1, axis=0) # median by col

array([4., 5.])